<a href="https://colab.research.google.com/github/sejeong-park/2020-AI/blob/master/%ED%95%B4%EB%B9%99%20%EC%A0%95%EB%8F%84%20%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip uninstall kaggle
!pip install --upgrade pip
!pip install kaggle==1.5.6

Uninstalling kaggle-1.5.6:
  Would remove:
    /usr/local/bin/kaggle
    /usr/local/lib/python3.6/dist-packages/kaggle-1.5.6.dist-info/*
    /usr/local/lib/python3.6/dist-packages/kaggle/*
Proceed (y/n)? ㅛ
Your response ('ㅛ') was not one of the expected responses: y, n
Proceed (y/n)? y
  Successfully uninstalled kaggle-1.5.6
Collecting pip
  Downloading https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 6.9MB/s
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
Successfully installed pip-20.1.1
Collecting kaggle==1.5.6
  Downloading kaggle-1.5.6.tar.gz (58 kB)
     |████████████████████████████████| 58 kB 3.5 MB/s
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from kaggle==1.5.6) (1.24.3)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.6/dist-packages (from kaggle==1.5.6) (1.12.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from kaggle==1.5.6) (2020.4.5.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from kaggle==1.5.6) (2.8.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from kaggle==1.5.6) (2.23.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from kaggle==1.5.6) (4.41.1)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.6/dist-packages (from kaggle==1.5.6) (4.0.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle==1.5.6) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle==1.5.6) (2.9)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.6/dist-packages (from python-slugify->kaggle==1.5.6) (1.3)
Building wheels for collected packages: kaggle
  Building wheel for kaggle (setup.py) ... done
  Created wheel for kaggle: filename=kaggle-1.5.6-py3-none-any.whl size=72859 sha256=e7bbbe1436e9dfabc5494534e265db77a0f3fa0cf3787fa0c34c0e8ead8a8830
  Stored in directory: /root/.cache/pip/wheels/01/3e/ff/77407ebac3ef71a79b9166a8382aecf88415a0bcbe3c095a01
Successfully built kaggle
Installing collected packages: kaggle
Successfully installed kaggle-1.5.6

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle
!ls -lha kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

-rw-r--r-- 1 root root 67 Jun 15 08:51 kaggle.json

In [ ]:
! kaggle competitions download -c prediction-of-sea-ice

Downloading prediction-of-sea-ice.zip to /content
  0% 0.00/12.8k [00:00<?, ?B/s]
100% 12.8k/12.8k [00:00<00:00, 9.62MB/s]

In [ ]:
!unzip prediction-of-sea-ice.zip

Archive:  prediction-of-sea-ice.zip
  inflating: seaice_sample.csv
  inflating: seaice_test.csv
  inflating: seaice_train.csv

In [ ]:
from sklearn.preprocessing import RobustScaler
import pandas as pd
import torch
import torch.optim as optim
import numpy as np
import random
torch.manual_seed(1)

In [ ]:
seaice_data = pd.read_csv('seaice_train.csv')

In [ ]:
seaice_data

     year  month   car_reg           cow          gdp_  Carbon  seaice_extent
0    1978     11    47.000  1.211070e+14  7.214118e+06  333.99      11.645133
1    1978     12    48.000  1.211070e+14  7.618305e+06  335.26      13.605867
2    1979      1    49.000  1.211070e+09  8.022491e+06  336.22      15.414000
3    1979      2    49.275  1.211565e+09  8.092499e+06  336.96      16.175286
4    1979      3    49.550  1.212061e+09  8.162507e+06  337.80      16.341938
..    ...    ...       ...           ...           ...     ...            ...
470  2019      1  2368.000  1.496833e+09  6.293426e+07     NaN      13.555677
471  2019      2  2370.300  1.496643e+09  6.307988e+07     NaN      14.398357
472  2019      3  2372.600  1.496452e+09  6.322549e+07     NaN      14.551968
473  2019      4  2374.900  1.496262e+09  6.337111e+07     NaN      13.454600
474  2019      5  2377.200  1.496072e+09  6.351673e+07     NaN      12.185733

[475 rows x 7 columns]

In [ ]:
from datetime import datetime as dt
from dateutil.parser import parse
import time

In [ ]:
def toYearFraction(date):
    def sinceEpoch(date): # returns seconds since epoch
        return time.mktime(date.timetuple())
    s = sinceEpoch

    year = date.year
    startOfThisYear = dt(year=year, month=1, day=1)
    startOfNextYear = dt(year=year+1, month=1, day=1)
    yearElapsed = s(date) - s(startOfThisYear)
    yearDuration = s(startOfNextYear) - s(startOfThisYear)
    # 초단위로 1년 / 현재날짜 의 비율 
    fraction = yearElapsed/yearDuration
    return date.year + fraction

In [ ]:
train_decimal_year = []

train_decimal_year.append(toYearFraction(parse("1978-11-15")))
train_decimal_year.append(toYearFraction(parse("1978-12-15")))

for i in range(1979, 2019):
  if i == 2016:
    continue
  for m in range(1 , 13):
    flag = int(m / 10)
    if flag == 0:
      date = ("{}-0{}-15".format(i,m))
    else:
      date = ("{}-{}-15".format(i,m))
    train_decimal_year.append(toYearFraction(parse(date)))

train_decimal_year.append(toYearFraction(parse("2019-01-15")))
train_decimal_year.append(toYearFraction(parse("2019-02-15")))
train_decimal_year.append(toYearFraction(parse("2019-03-15")))
train_decimal_year.append(toYearFraction(parse("2019-04-15")))
train_decimal_year.append(toYearFraction(parse("2019-05-15")))

In [ ]:
train_decimal_year = np.array(train_decimal_year)
train_decimal_year.shape

(475,)

In [ ]:
seaice_data = seaice_data.drop(['month'],axis = 1)

In [ ]:
for i in range(475):
  seaice_data.iloc[i,0] = train_decimal_year[i]

In [ ]:
seaice_data.tail(30)
seaice_data.iloc[447:475]

            year     car_reg           cow         gdp_  Carbon  seaice_extent
447  2017.123288  2258.61667  1.474659e+09  58654437.47     NaN      14.119429
448  2017.200000  2264.23333  1.476030e+09  58854796.29     NaN      14.290065
449  2017.284932  2269.85000  1.477401e+09  59055155.10     NaN      13.753467
450  2017.367123  2275.46667  1.478773e+09  59255513.91     NaN      12.630452
451  2017.452055  2281.08333  1.480144e+09  59455872.72     NaN      10.756400
452  2017.534247  2286.70000  1.481516e+09  59656231.54     NaN       7.939355
453  2017.619178  2292.31667  1.482887e+09  59856590.35     NaN       5.480645
454  2017.704110  2297.93333  1.484259e+09  60056949.16     NaN       4.821900
455  2017.786301  2303.55000  1.485630e+09  60257307.97     NaN       6.767129
456  2017.871233  2309.16667  1.487002e+09  60457666.79     NaN       9.492833
457  2017.953425  2314.78333  1.488373e+09  60658025.60     NaN      11.720867
458  2018.038356  2320.00000  1.489745e+09  60858384.41     NaN      13.056645
459  2018.123288  2323.95833  1.490335e+09  61031373.66     NaN      13.945893
460  2018.200000  2327.91667  1.490926e+09  61204362.91     NaN      14.298323
461  2018.284932  2331.87500  1.491517e+09  61377352.16     NaN      13.708667
462  2018.367123  2335.83333  1.492107e+09  61550341.41     NaN      12.208613
463  2018.452055  2339.79167  1.492698e+09  61723330.66     NaN      10.708533
464  2018.534247  2343.75000  1.493289e+09  61896319.91     NaN       8.224355
465  2018.619178  2347.70833  1.493879e+09  62069309.15     NaN       5.607935
466  2018.704110  2351.66667  1.494470e+09  62242298.40     NaN       4.713600
467  2018.786301  2355.62500  1.495061e+09  62415287.65     NaN       6.063484
468  2018.871233  2359.58333  1.495651e+09  62588276.90     NaN       9.804700
469  2018.953425  2363.54167  1.496242e+09  62761266.15     NaN      11.831933
470  2019.038356  2368.00000  1.496833e+09  62934255.40     NaN      13.555677
471  2019.123288  2370.30000  1.496643e+09  63079875.09     NaN      14.398357
472  2019.200000  2372.60000  1.496452e+09  63225494.77     NaN      14.551968
473  2019.284932  2374.90000  1.496262e+09  63371114.46     NaN      13.454600
474  2019.367123  2377.20000  1.496072e+09  63516734.14     NaN      12.185733

In [ ]:
x_carbon = np.array(seaice_data.iloc[0:447,0:4])
x_seaice = np.array(seaice_data.iloc[0:447,5])
y_carbon = np.array(seaice_data.iloc[0:447,4])

In [ ]:
x_carbon

array([[1.97887123e+03, 4.70000000e+01, 1.21107000e+14, 7.21411850e+06],
       [1.97895342e+03, 4.80000000e+01, 1.21107000e+14, 7.61830475e+06],
       [1.97903836e+03, 4.90000000e+01, 1.21106969e+09, 8.02249138e+06],
       ...,
       [2.01587123e+03, 2.16675000e+03, 1.46518016e+09, 5.55059597e+07],
       [2.01595342e+03, 2.17352500e+03, 1.46678969e+09, 5.56851165e+07],
       [2.01703836e+03, 2.25300000e+03, 1.47328713e+09, 5.84540787e+07]])

In [ ]:
scaler = RobustScaler()
x_carbon_s = scaler.fit_transform(x_carbon)

In [ ]:
x_carbon_s

array([[-9.99902314e-01, -7.03654222e-01,  9.73414858e+05,
        -7.36492798e-01],
       [-9.95479273e-01, -7.02947978e-01,  9.73414858e+05,
        -7.20516815e-01],
       [-9.90908796e-01, -7.02241734e-01, -8.77534553e-01,
        -7.04540817e-01],
       ...,
       [ 9.91203666e-01,  7.93406040e-01,  1.16493702e+00,
         1.17230452e+00],
       [ 9.95626707e-01,  7.98190842e-01,  1.17787400e+00,
         1.17938592e+00],
       [ 1.05401086e+00,  8.54319567e-01,  1.23009863e+00,
         1.28883273e+00]])

In [ ]:
x_ctrain = torch.FloatTensor(x_carbon_s)
y_ctrain = torch.FloatTensor(np.transpose(y_carbon[np.newaxis]))

In [ ]:
x_ctrain

tensor([[-9.9990e-01, -7.0365e-01,  9.7341e+05, -7.3649e-01],
        [-9.9548e-01, -7.0295e-01,  9.7341e+05, -7.2052e-01],
        [-9.9091e-01, -7.0224e-01, -8.7753e-01, -7.0454e-01],
        ...,
        [ 9.9120e-01,  7.9341e-01,  1.1649e+00,  1.1723e+00],
        [ 9.9563e-01,  7.9819e-01,  1.1779e+00,  1.1794e+00],
        [ 1.0540e+00,  8.5432e-01,  1.2301e+00,  1.2888e+00]])

In [ ]:
y_ctrain

tensor([[333.9900],
        [335.2600],
        [336.2200],
        [336.9600],
        [337.8000],
        [339.0400],
        [339.6500],
        [339.0500],
        [337.6400],
        [335.6900],
        [334.1100],
        [334.1700],
        [335.5200],
        [336.8600],
        [337.8800],
        [338.6800],
        [339.6000],
        [340.8700],
        [341.4800],
        [340.8700],
        [339.4500],
        [337.4900],
        [335.9000],
        [335.9300],
        [337.2400],
        [338.5200],
        [339.4700],
        [340.2100],
        [341.0400],
        [342.2400],
        [342.8200],
        [342.1500],
        [340.6900],
        [338.6700],
        [337.0300],
        [337.0400],
        [338.3600],
        [339.6600],
        [340.6300],
        [341.3700],
        [342.2000],
        [343.4100],
        [343.9900],
        [343.3100],
        [341.8300],
        [339.8000],
        [338.1400],
        [338.1400],
        [339.4600],
        [340.7800],
        [341.8000],
        [342.6100],
        [343.5200],
        [344.8400],
        [345.5300],
        [344.9700],
        [343.5900],
        [341.6400],
        [340.0500],
        [340.1000],
        [341.4600],
        [342.7900],
        [343.7900],
        [344.5600],
        [345.4600],
        [346.7200],
        [347.3100],
        [346.6500],
        [345.2000],
        [343.1900],
        [341.5700],
        [341.6100],
        [342.9600],
        [344.2800],
        [345.2800],
        [346.0600],
        [346.9300],
        [348.1800],
        [348.7900],
        [348.1300],
        [346.6500],
        [344.6100],
        [342.9300],
        [342.9300],
        [344.2400],
        [345.5300],
        [346.5000],
        [347.2500],
        [348.1100],
        [349.3700],
        [350.0000],
        [349.3700],
        [347.9100],
        [345.9000],
        [344.2600],
        [344.2900],
        [345.6400],
        [346.9800],
        [348.0000],
        [348.8100],
        [349.7100],
        [351.0400],
        [351.7300],
        [351.1700],
        [349.7900],
        [347.8600],
        [346.3100],
        [346.4300],
        [347.8800],
        [349.3200],
        [350.4200],
        [351.2900],
        [352.2800],
        [353.6300],
        [354.3000],
        [353.7000],
        [352.2800],
        [350.2900],
        [348.6800],
        [348.7400],
        [350.1000],
        [351.4300],
        [352.4200],
        [353.1800],
        [354.0300],
        [355.2800],
        [355.8900],
        [355.2200],
        [353.7200],
        [351.6500],
        [349.9600],
        [349.9700],
        [351.3000],
        [352.6200],
        [353.6100],
        [354.3600],
        [355.2200],
        [356.4700],
        [357.0800],
        [356.4200],
        [354.9500],
        [352.9100],
        [351.2600],
        [351.3100],
        [352.7000],
        [354.0700],
        [355.1100],
        [355.9100],
        [356.7900],
        [358.0600],
        [358.6600],
        [357.9700],
        [356.4300],
        [354.3000],
        [352.5600],
        [352.5300],
        [353.8400],
        [355.1300],
        [356.0900],
        [356.8200],
        [357.6800],
        [358.9100],
        [359.4400],
        [358.6900],
        [357.1100],
        [354.9600],
        [353.2000],
        [353.1500],
        [354.4400],
        [355.7100],
        [356.6500],
        [357.3700],
        [358.2000],
        [359.4400],
        [360.0400],
        [359.3500],
        [357.8300],
        [355.7500],
        [354.0600],
        [354.1100],
        [355.5100],
        [356.9100],
        [357.9700],
        [358.8000],
        [359.7300],
        [361.0700],
        [361.7400],
        [361.1200],
        [359.6700],
        [357.6400],
        [356.0000],
        [356.0800],
        [357.5200],
        [358.9400],
        [360.0200],
        [360.8700],
        [361.8000],
        [363.1500],
        [363.8300],
        [363.2100],
        [361.7400],
        [359.6900],
        [358.0300],
        [358.0900],
        [359.5100],
        [360.9100],
        [361.9700],
        [362.7800],
        [363.7200],
        [365.0200],
        [365.6200],
        [364.9200],
        [363.3800],
        [361.2600],
        [359.5300],
        [359.5300],
        [360.8800],
        [362.2000],
        [363.1800],
        [363.9300],
        [364.8000],
        [366.0800],
        [366.7100],
        [366.0600],
        [364.5700],
        [362.5200],
        [360.8900],
        [361.0100],
        [362.5200],
        [364.0300],
        [365.2100],
        [366.1600],
        [367.1900],
        [368.6500],
        [369.4400],
        [368.9100],
        [367.5100],
        [365.5200],
        [363.9000],
        [363.9900],
        [365.4400],
        [366.8500],
        [367.8900],
        [368.6800],
        [369.5400],
        [370.8100],
        [371.4000],
        [370.6700],
        [369.0900],
        [366.9200],
        [365.1500],
        [365.1300],
        [366.5000],
        [367.8400],
        [368.8500],
        [369.6100],
        [370.5300],
        [371.8300],
        [372.4400],
        [371.7500],
        [370.2300],
        [368.1300],
        [366.4500],
        [366.5100],
        [367.9300],
        [369.3300],
        [370.3600],
        [371.1600],
        [372.0600],
        [373.3700],
        [374.0200],
        [373.3400],
        [371.8200],
        [369.7100],
        [368.0000],
        [368.0600],
        [369.5200],
        [370.9500],
        [372.0300],
        [372.8800],
        [373.8400],
        [375.2200],
        [375.9400],
        [375.3500],
        [373.9000],
        [371.8700],
        [370.2400],
        [370.3700],
        [371.9000],
        [373.4000],
        [374.5400],
        [375.4400],
        [376.4300],
        [377.8500],
        [378.5800],
        [377.9800],
        [376.5000],
        [374.4200],
        [372.7300],
        [372.8000],
        [374.2600],
        [375.6800],
        [376.7400],
        [377.5600],
        [378.5000],
        [379.8300],
        [380.4400],
        [379.7300],
        [378.1700],
        [376.0300],
        [374.3200],
        [374.4000],
        [375.8800],
        [377.3500],
        [378.4800],
        [379.3800],
        [380.3800],
        [381.8100],
        [382.5600],
        [381.9700],
        [380.5000],
        [378.4300],
        [376.7600],
        [376.8600],
        [378.3600],
        [379.8400],
        [380.9500],
        [381.8100],
        [382.7600],
        [384.1300],
        [384.8100],
        [384.1400],
        [382.6000],
        [380.4600],
        [378.7200],
        [378.7600],
        [380.2200],
        [381.6600],
        [382.7400],
        [383.5900],
        [384.5400],
        [385.9200],
        [386.6100],
        [385.9600],
        [384.4300],
        [382.3000],
        [380.5600],
        [380.6200],
        [382.0900],
        [383.5400],
        [384.6200],
        [385.4500],
        [386.4300],
        [387.8000],
        [388.4700],
        [387.8000],
        [386.2600],
        [384.1300],
        [382.4200],
        [382.4900],
        [383.9600],
        [385.4100],
        [386.5000],
        [387.3500],
        [388.3000],
        [389.7000],
        [390.4000],
        [389.7600],
        [388.2500],
        [386.1400],
        [384.4400],
        [384.5500],
        [386.1000],
        [387.6300],
        [388.8000],
        [389.7200],
        [390.7300],
        [392.1700],
        [392.9000],
        [392.2600],
        [390.7300],
        [388.5800],
        [386.8300],
        [386.8900],
        [388.3600],
        [389.8000],
        [390.8800],
        [391.7100],
        [392.6400],
        [394.0100],
        [394.6900],
        [394.0200],
        [392.4800],
        [390.3300],
        [388.5900],
        [388.6700],
        [390.1800],
        [391.6700],
        [392.8000],
        [393.6900],
        [394.7200],
        [396.1500],
        [396.8700],
        [396.2400],
        [394.7300],
        [392.6400],
        [390.9700],
        [391.1300],
        [392.7100],
        [394.2500],
        [395.4300],
        [396.3600],
        [397.3800],
        [398.8400],
        [399.5900],
        [398.9600],
        [397.4300],
        [395.2800],
        [393.5400],
        [393.6200],
        [395.1300],
        [396.6200],
        [397.7500],
        [398.6200],
        [399.6000],
        [401.0100],
        [401.7200],
        [401.0400],
        [399.4700],
        [397.2900],
        [395.5100],
        [395.5800],
        [397.1000],
        [398.6000],
        [399.7300],
        [400.6300],
        [401.6400],
        [403.1000],
        [403.8600],
        [403.2500],
        [401.7600],
        [399.6800],
        [398.0300],
        [398.2300],
        [399.9000],
        [401.5400],
        [405.8700]])

In [ ]:
W = torch.zeros((4,1),requires_grad=True)
b = torch.zeros(1,requires_grad=True)

In [ ]:
import torch.nn.functional as F
optimizer = optim.Adam([W,b], lr = 0.1)
loss = torch.nn.MSELoss()

nb_epochs = 100000
for epochs in range(nb_epochs + 1):
  h = x_ctrain.matmul(W)+ b
  cost = loss(h,y_ctrain)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epochs % 1000 == 0:
    print("epochs {}/{:4d}, cost {:.6f}".format(epochs, nb_epochs, cost.item()))

epochs 0/100000, cost 134440.484375
epochs 1000/100000, cost 70788.914062
epochs 2000/100000, cost 31711.923828
epochs 3000/100000, cost 11228.016602
epochs 4000/100000, cost 2865.727295
epochs 5000/100000, cost 655.416138
epochs 6000/100000, cost 362.652435
epochs 7000/100000, cost 322.211243
epochs 8000/100000, cost 87414.570312
epochs 9000/100000, cost 267.119904
epochs 10000/100000, cost 240.671463
epochs 11000/100000, cost 4737.510742
epochs 12000/100000, cost 197.654449
epochs 13000/100000, cost 179.114777
epochs 14000/100000, cost 107875.375000
epochs 15000/100000, cost 148.353561
epochs 16000/100000, cost 134.022751
epochs 17000/100000, cost 121.649582
epochs 18000/100000, cost 112.311974
epochs 19000/100000, cost 100.485497
epochs 20000/100000, cost 91.316338
epochs 21000/100000, cost 1435.713623
epochs 22000/100000, cost 75.653687
epochs 23000/100000, cost 68.967987
epochs 24000/100000, cost 62.888599
epochs 25000/100000, cost 57.391586
epochs 26000/100000, cost 25020.695312
epochs 27000/100000, cost 47.914478
epochs 28000/100000, cost 43.805256
epochs 29000/100000, cost 40.145348
epochs 30000/100000, cost 167.855728
epochs 31000/100000, cost 33.773838
epochs 32000/100000, cost 31.042297
epochs 33000/100000, cost 37.324467
epochs 34000/100000, cost 167.789795
epochs 35000/100000, cost 24.320393
epochs 36000/100000, cost 22.482714
epochs 37000/100000, cost 106.904282
epochs 38000/100000, cost 19.326342
epochs 39000/100000, cost 17.963961
epochs 40000/100000, cost 42.148254
epochs 41000/100000, cost 15.639568
epochs 42000/100000, cost 14.637580
epochs 43000/100000, cost 13.745556
epochs 44000/100000, cost 480.910004
epochs 45000/100000, cost 19.468493
epochs 46000/100000, cost 11.493649
epochs 47000/100000, cost 44.760494
epochs 48000/100000, cost 157.451218
epochs 49000/100000, cost 9.831369
epochs 50000/100000, cost 9.377081
epochs 51000/100000, cost 8687.665039
epochs 52000/100000, cost 8.691927
epochs 53000/100000, cost 8.261894
epochs 54000/100000, cost 7.955608
epochs 55000/100000, cost 560776.750000
epochs 56000/100000, cost 8.057113
epochs 57000/100000, cost 7.203892
epochs 58000/100000, cost 6.997055
epochs 59000/100000, cost 266283.750000
epochs 60000/100000, cost 6.758278
epochs 61000/100000, cost 6.487893
epochs 62000/100000, cost 6.347589
epochs 63000/100000, cost 571.224731
epochs 64000/100000, cost 6.107340
epochs 65000/100000, cost 6.000570
epochs 66000/100000, cost 2933.550537
epochs 67000/100000, cost 5.887218
epochs 68000/100000, cost 5.740790
epochs 69000/100000, cost 5.670683
epochs 70000/100000, cost 1460.417603
epochs 71000/100000, cost 5.551916
epochs 72000/100000, cost 5.490997
epochs 73000/100000, cost 6.938560
epochs 74000/100000, cost 5.397036
epochs 75000/100000, cost 5.356378
epochs 76000/100000, cost 32.963654
epochs 77000/100000, cost 5.285211
epochs 78000/100000, cost 5.254172
epochs 79000/100000, cost 9.402151
epochs 80000/100000, cost 5.199615
epochs 81000/100000, cost 5.175807
epochs 82000/100000, cost 5.178469
epochs 83000/100000, cost 37.372112
epochs 84000/100000, cost 5.116650
epochs 85000/100000, cost 5.099065
epochs 86000/100000, cost 4696.295410
epochs 87000/100000, cost 5.095062
epochs 88000/100000, cost 5.056335
epochs 89000/100000, cost 5.044412
epochs 90000/100000, cost 7.231867
epochs 91000/100000, cost 5.022901
epochs 92000/100000, cost 5.013393
epochs 93000/100000, cost 523.952637
epochs 94000/100000, cost 4.999165
epochs 95000/100000, cost 4.989139
epochs 96000/100000, cost 12.111190
epochs 97000/100000, cost 4.975723
epochs 98000/100000, cost 116788.835938
epochs 99000/100000, cost 97.088921
epochs 100000/100000, cost 4.959033

In [ ]:
carbon_x_test = np.array(seaice_data.iloc[447:475,0:4])
carbon_xs_test = scaler.fit_transform(carbon_x_test)
carbon_xs_test

array([[-0.99512789, -1.18629724, -1.46670285, -1.07535441],
       [-0.92691839, -1.09281932, -1.34525428, -0.99363119],
       [-0.85140073, -0.99934123, -1.22380572, -0.91190797],
       [-0.77831912, -0.90586314, -1.10235715, -0.83018475],
       [-0.70280146, -0.81238522, -0.98090858, -0.74846154],
       [-0.62971985, -0.71890713, -0.85945993, -0.66673831],
       [-0.55420219, -0.62542904, -0.73801136, -0.5850151 ],
       [-0.47868453, -0.53195112, -0.6165628 , -0.50329188],
       [-0.40560292, -0.43847303, -0.49511423, -0.42156866],
       [-0.33008526, -0.34499494, -0.37366567, -0.33984544],
       [-0.25700365, -0.25151702, -0.2522171 , -0.25812222],
       [-0.18148599, -0.16469612, -0.13076854, -0.17639901],
       [-0.10596833, -0.09881774, -0.07846114, -0.1058394 ],
       [-0.03775883, -0.03293919, -0.02615374, -0.0352798 ],
       [ 0.03775883,  0.03293919,  0.02615374,  0.0352798 ],
       [ 0.11084044,  0.09881757,  0.07846114,  0.1058394 ],
       [ 0.1863581 ,  0.16469612,  0.13076854,  0.17639901],
       [ 0.25943971,  0.2305745 ,  0.18307593,  0.24695861],
       [ 0.33495737,  0.29645288,  0.23538333,  0.31751821],
       [ 0.41047503,  0.36233143,  0.28769073,  0.38807781],
       [ 0.48355664,  0.42820981,  0.33999821,  0.45863741],
       [ 0.5590743 ,  0.49408819,  0.39230561,  0.52919702],
       [ 0.63215591,  0.55996673,  0.444613  ,  0.59975662],
       [ 0.70767357,  0.6341666 ,  0.4969204 ,  0.67031622],
       [ 0.78319123,  0.67244544,  0.48008672,  0.72971221],
       [ 0.85140073,  0.71072428,  0.46325294,  0.7891082 ],
       [ 0.92691839,  0.74900312,  0.44641917,  0.84850418],
       [ 1.        ,  0.78728196,  0.4295854 ,  0.90790017]])

In [ ]:
x_ctest = torch.FloatTensor(carbon_xs_test)
carbon_pred = x_ctest.matmul(W)+b
carbon_pred = carbon_pred.detach().numpy()

In [ ]:
carbon_pred

array([[329.22928],
       [331.75714],
       [334.37436],
       [336.9618 ],
       [339.579  ],
       [342.16644],
       [344.78366],
       [347.40088],
       [349.9883 ],
       [352.60553],
       [355.19296],
       [357.83054],
       [360.26172],
       [362.60352],
       [365.03473],
       [367.4361 ],
       [369.86728],
       [372.26868],
       [374.69986],
       [377.13104],
       [379.53244],
       [381.96362],
       [384.36502],
       [386.77078],
       [389.01593],
       [391.1717 ],
       [393.41684],
       [395.6322 ]], dtype=float32)

In [ ]:
index = 0
for i in range(447,475):
   seaice_data.iloc[i,4] = carbon_pred[index]
   index = index + 1

In [ ]:
x_data = np.array(seaice_data.iloc[:,0:5])
xs_data = scaler.fit_transform(x_data)
y_data = np.transpose(np.array(seaice_data.iloc[:,5])[np.newaxis])

In [ ]:
x_train = torch.FloatTensor(xs_data)
y_train = torch.FloatTensor(y_data)

In [ ]:
x_train

tensor([[-9.9997e-01, -7.1508e-01,  9.7430e+05, -7.5721e-01, -9.3770e-01],
        [-9.9580e-01, -7.1439e-01,  9.7430e+05, -7.4180e-01, -8.9806e-01],
        [-9.9150e-01, -7.1370e-01, -8.9708e-01, -7.2640e-01, -8.6809e-01],
        ...,
        [ 1.0421e+00,  8.8320e-01,  1.3988e+00,  1.3773e+00,  8.4723e-01],
        [ 1.0464e+00,  8.8478e-01,  1.3973e+00,  1.3829e+00,  9.1731e-01],
        [ 1.0506e+00,  8.8636e-01,  1.3958e+00,  1.3884e+00,  9.8646e-01]])

In [ ]:
y_train

tensor([[11.6451],
        [13.6059],
        [15.4140],
        [16.1753],
        [16.3419],
        [15.4468],
        [13.8569],
        [12.5300],
        [10.3112],
        [ 8.0411],
        [ 7.0511],
        [ 8.7479],
        [10.9431],
        [13.2823],
        [14.8619],
        [15.9551],
        [16.0413],
        [15.4291],
        [13.7926],
        [12.2046],
        [10.1001],
        [ 7.9843],
        [ 7.6671],
        [ 9.1827],
        [11.3829],
        [13.5572],
        [14.9097],
        [15.6041],
        [15.6315],
        [15.0099],
        [13.8016],
        [12.4297],
        [10.2710],
        [ 7.8443],
        [ 7.1385],
        [ 8.8563],
        [10.9290],
        [13.2823],
        [15.1767],
        [15.9735],
        [16.0439],
        [15.4660],
        [13.9732],
        [12.4761],
        [10.3671],
        [ 8.1395],
        [ 7.3017],
        [ 9.4211],
        [11.6275],
        [13.6049],
        [14.9424],
        [16.0061],
        [16.0853],
        [15.1721],
        [13.4913],
        [12.2957],
        [10.5703],
        [ 8.1859],
        [ 7.3946],
        [ 9.3341],
        [11.4610],
        [13.2579],
        [14.4733],
        [15.2989],
        [15.5842],
        [15.0145],
        [13.5767],
        [12.1517],
        [ 9.9775],
        [ 7.7711],
        [ 6.8052],
        [ 8.5606],
        [10.8415],
        [12.9361],
        [14.7249],
        [15.4657],
        [15.8859],
        [15.3565],
        [14.0734],
        [12.2191],
        [ 9.7446],
        [ 7.4019],
        [ 6.6977],
        [ 8.5459],
        [11.0245],
        [13.0034],
        [14.8896],
        [15.7849],
        [15.9095],
        [15.0588],
        [13.3796],
        [11.9759],
        [10.1465],
        [ 7.9796],
        [ 7.4107],
        [ 9.4839],
        [11.4533],
        [13.1647],
        [14.9698],
        [16.0501],
        [15.8159],
        [15.2109],
        [13.7429],
        [12.4857],
        [10.3326],
        [ 7.4999],
        [ 7.2787],
        [ 9.0488],
        [11.2240],
        [12.4970],
        [15.0905],
        [15.5834],
        [15.9572],
        [15.1233],
        [13.5609],
        [11.9434],
        [ 9.8087],
        [ 7.8916],
        [ 7.3690],
        [ 9.1350],
        [11.3308],
        [13.6060],
        [14.9548],
        [15.4955],
        [15.4233],
        [14.3284],
        [13.0441],
        [12.2445],
        [10.1297],
        [ 7.8818],
        [ 7.0083],
        [ 8.8289],
        [11.1152],
        [13.3631],
        [14.7826],
        [15.5782],
        [15.8667],
        [14.6501],
        [13.2258],
        [11.6406],
        [ 9.2466],
        [ 6.7975],
        [ 6.1428],
        [ 8.4849],
        [11.0752],
        [13.0929],
        [14.3638],
        [15.2494],
        [15.4161],
        [14.8597],
        [13.4731],
        [12.1080],
        [ 9.5140],
        [ 7.4154],
        [ 6.4729],
        [ 8.5414],
        [10.8846],
        [12.9135],
        [14.6427],
        [15.4621],
        [15.4811],
        [14.6769],
        [13.2155],
        [12.1468],
        [10.3231],
        [ 7.9253],
        [ 7.4737],
        [ 9.3195],
        [11.3787],
        [13.3895],
        [14.8961],
        [15.6856],
        [15.8132],
        [15.0772],
        [13.3682],
        [11.8709],
        [ 9.4764],
        [ 7.3350],
        [ 6.3967],
        [ 8.7861],
        [11.3187],
        [13.2974],
        [14.7298],
        [15.5619],
        [15.5536],
        [14.8880],
        [13.6244],
        [12.0164],
        [ 9.9252],
        [ 7.6393],
        [ 7.1376],
        [ 8.9153],
        [11.1232],
        [13.2440],
        [14.5864],
        [15.2257],
        [15.2602],
        [14.4486],
        [12.9721],
        [11.4404],
        [ 8.9871],
        [ 6.7444],
        [ 6.0801],
        [ 7.8289],
        [10.7609],
        [12.8948],
        [14.1809],
        [15.1548],
        [15.1228],
        [14.2159],
        [13.0945],
        [12.0838],
        [10.1643],
        [ 8.1805],
        [ 7.5825],
        [ 9.1610],
        [10.4017],
        [12.8349],
        [14.4175],
        [15.4367],
        [15.4675],
        [14.5630],
        [13.1772],
        [11.7384],
        [ 9.4108],
        [ 7.2850],
        [ 6.6863],
        [ 8.3365],
        [10.6842],
        [13.0473],
        [14.7205],
        [15.7458],
        [15.5981],
        [14.8919],
        [13.5898],
        [11.7057],
        [ 9.4152],
        [ 7.5089],
        [ 6.5360],
        [ 8.4519],
        [10.4406],
        [12.7246],
        [14.3594],
        [15.3089],
        [15.3977],
        [15.0839],
        [13.7510],
        [11.7792],
        [ 9.4883],
        [ 7.2256],
        [ 6.1169],
        [ 8.6028],
        [10.7965],
        [12.6175],
        [14.2204],
        [15.1415],
        [15.2248],
        [14.5582],
        [13.1527],
        [11.6652],
        [ 9.5130],
        [ 7.1683],
        [ 6.2461],
        [ 8.3794],
        [10.3211],
        [12.6098],
        [14.2026],
        [15.2111],
        [15.5163],
        [14.8568],
        [13.5096],
        [11.4559],
        [ 9.0704],
        [ 7.4608],
        [ 6.7322],
        [ 8.2983],
        [10.6578],
        [12.4564],
        [14.2726],
        [15.3424],
        [15.3489],
        [14.2994],
        [12.9706],
        [11.5834],
        [ 9.2742],
        [ 6.5990],
        [ 5.8271],
        [ 8.1619],
        [10.3419],
        [12.5786],
        [14.3908],
        [15.1931],
        [15.4849],
        [14.5121],
        [13.0161],
        [11.6040],
        [ 9.2148],
        [ 6.9359],
        [ 6.1161],
        [ 7.8483],
        [10.1253],
        [12.5617],
        [14.0264],
        [14.9144],
        [14.9926],
        [13.9873],
        [12.5584],
        [11.4471],
        [ 9.4314],
        [ 6.8548],
        [ 5.9845],
        [ 7.9253],
        [10.3433],
        [12.5381],
        [13.6615],
        [14.3729],
        [14.6866],
        [14.0898],
        [12.9111],
        [11.1620],
        [ 8.6487],
        [ 6.3011],
        [ 5.5038],
        [ 7.3520],
        [10.2163],
        [12.1997],
        [13.4656],
        [14.3250],
        [14.4210],
        [13.9059],
        [12.5174],
        [10.9195],
        [ 8.4598],
        [ 6.4956],
        [ 5.8624],
        [ 7.5411],
        [ 9.6587],
        [11.9174],
        [13.7030],
        [14.5133],
        [14.5421],
        [13.8452],
        [12.7797],
        [11.2201],
        [ 7.9428],
        [ 5.3423],
        [ 4.2673],
        [ 6.0397],
        [ 9.7602],
        [12.0000],
        [13.8873],
        [14.9534],
        [15.1789],
        [14.3519],
        [12.9740],
        [11.2083],
        [ 8.6779],
        [ 5.9131],
        [ 4.6874],
        [ 7.3499],
        [10.3429],
        [12.3355],
        [13.9137],
        [14.8115],
        [14.9836],
        [14.4956],
        [13.1867],
        [11.3203],
        [ 8.4655],
        [ 6.1357],
        [ 5.2616],
        [ 6.9203],
        [ 9.7717],
        [12.1712],
        [13.7391],
        [14.5814],
        [15.1367],
        [14.6587],
        [12.8661],
        [10.5851],
        [ 8.0747],
        [ 5.8749],
        [ 4.8651],
        [ 6.9839],
        [ 9.6140],
        [11.8029],
        [13.4640],
        [14.3630],
        [14.5465],
        [14.1078],
        [12.6808],
        [10.7487],
        [ 7.7244],
        [ 5.5025],
        [ 4.5613],
        [ 6.4645],
        [ 9.7718],
        [12.1194],
        [13.7294],
        [14.5533],
        [15.1963],
        [14.6258],
        [13.0118],
        [10.6745],
        [ 7.6718],
        [ 4.7233],
        [ 3.5656],
        [ 5.8859],
        [ 9.3880],
        [11.9765],
        [13.7026],
        [14.7235],
        [15.0320],
        [14.2987],
        [12.9973],
        [11.3601],
        [ 8.1317],
        [ 6.0135],
        [ 5.2083],
        [ 7.4548],
        [ 9.9390],
        [12.1629],
        [13.6475],
        [14.4176],
        [14.7575],
        [14.0879],
        [12.7007],
        [11.0326],
        [ 8.1085],
        [ 6.0779],
        [ 5.2199],
        [ 7.2325],
        [10.1146],
        [12.3295],
        [13.6023],
        [14.4006],
        [14.3705],
        [13.8932],
        [12.4681],
        [10.8789],
        [ 8.3779],
        [ 5.5987],
        [ 4.6158],
        [ 6.9662],
        [ 9.8462],
        [12.0218],
        [13.1901],
        [14.1194],
        [14.2901],
        [13.7535],
        [12.6305],
        [10.7564],
        [ 7.9394],
        [ 5.4806],
        [ 4.8219],
        [ 6.7671],
        [ 9.4928],
        [11.7209],
        [13.0566],
        [13.9459],
        [14.2983],
        [13.7087],
        [12.2086],
        [10.7085],
        [ 8.2244],
        [ 5.6079],
        [ 4.7136],
        [ 6.0635],
        [ 9.8047],
        [11.8319],
        [13.5557],
        [14.3984],
        [14.5520],
        [13.4546],
        [12.1857]])

In [ ]:
x_W = torch.zeros((5,1), requires_grad=True)
x_b = torch.zeros(1, requires_grad=True)

In [ ]:
optimizer_1 = optim.Adam([x_W,x_b], lr = 1e-3)
loss = torch.nn.MSELoss()

nb_epochs = 50000
for epochs in range(nb_epochs + 1):
  h_1 = x_train.matmul(x_W)+ x_b

  cost_1 = loss(h_1,y_train)
  optimizer_1.zero_grad()
  cost_1.backward()
  optimizer_1.step()

  if epochs % 1000 == 0:
    print("epochs {}/{:4d}, cost {:.6f}".format(epochs, nb_epochs, cost_1.item()))

epochs 0/50000, cost 142.927872
epochs 1000/50000, cost 117.434166
epochs 2000/50000, cost 95.692879
epochs 3000/50000, cost 77.065063
epochs 4000/50000, cost 61.239849
epochs 5000/50000, cost 47.958187
epochs 6000/50000, cost 60.015392
epochs 7000/50000, cost 28.298645
epochs 8000/50000, cost 21.581720
epochs 9000/50000, cost 16.684219
epochs 10000/50000, cost 13.415312
epochs 11000/50000, cost 11.509745
epochs 12000/50000, cost 10.592340
epochs 13000/50000, cost 15.059517
epochs 14000/50000, cost 10.168923
epochs 15000/50000, cost 10.115709
epochs 16000/50000, cost 10.070675
epochs 17000/50000, cost 10.028770
epochs 18000/50000, cost 9.992998
epochs 19000/50000, cost 9.957221
epochs 20000/50000, cost 25.196218
epochs 21000/50000, cost 9.898582
epochs 22000/50000, cost 11.381709
epochs 23000/50000, cost 9.850769
epochs 24000/50000, cost 17.874884
epochs 25000/50000, cost 9.811983
epochs 26000/50000, cost 10.416400
epochs 27000/50000, cost 9.780699
epochs 28000/50000, cost 9.767356
epochs 29000/50000, cost 9.983041
epochs 30000/50000, cost 9.744659
epochs 31000/50000, cost 9.734962
epochs 32000/50000, cost 9.769753
epochs 33000/50000, cost 9.718634
epochs 34000/50000, cost 9.711621
epochs 35000/50000, cost 9.705382
epochs 36000/50000, cost 9.699730
epochs 37000/50000, cost 9.694799
epochs 38000/50000, cost 9.690253
epochs 39000/50000, cost 18.012625
epochs 40000/50000, cost 9.682602
epochs 41000/50000, cost 9.679347
epochs 42000/50000, cost 9.676456
epochs 43000/50000, cost 9.673841
epochs 44000/50000, cost 9.674584
epochs 45000/50000, cost 9.669453
epochs 46000/50000, cost 10.022959
epochs 47000/50000, cost 9.665926
epochs 48000/50000, cost 9.664421
epochs 49000/50000, cost 9.663117
epochs 50000/50000, cost 9.661885

In [ ]:
test_data = pd.read_csv('seaice_test.csv')
test_data

    year  month     car_reg         cow         gdp_  Carbon
0   2016      1  2180.00000  1468399225  55864273.29  402.82
1   2016      2  2186.04167  1468806550  56080090.40  403.84
2   2016      3  2192.08333  1469213875  56295907.52  404.98
3   2016      4  2198.12500  1469621201  56511724.63  406.51
4   2016      5  2204.16667  1470028526  56727541.75  407.28
5   2016      6  2210.20833  1470435851  56943358.86  406.66
6   2016      7  2216.25000  1470843176  57159175.98  405.14
7   2016      8  2222.29167  1471250501  57374993.09  403.02
8   2016      9  2228.33333  1471657826  57590810.20  401.33
9   2016     10  2234.37500  1472065152  57806627.32  401.48
10  2016     11  2240.41667  1472472477  58022444.43  403.08
11  2016     12  2246.45833  1472879802  58238261.55  404.66

In [ ]:
test_decimal_year = []

for m in range(1 , 13):
  flag = int(m / 10)
  if flag == 0:
    date = ("2016-0{}-15".format(m))
  else:
    date = ("2016-{}-15".format(m))
  test_decimal_year.append(toYearFraction(parse(date)))

test_decimal_year = np.array(test_decimal_year )
test_decimal_year

array([2016.03825137, 2016.12295082, 2016.20218579, 2016.28688525,
       2016.36885246, 2016.45355191, 2016.53551913, 2016.62021858,
       2016.70491803, 2016.78688525, 2016.8715847 , 2016.95355191])

In [ ]:
test_data = test_data.drop(['month'],axis = 1)

for i in range(12):
  test_data.iloc[i,0] = test_decimal_year[i]

In [ ]:
tests_data = scaler.fit_transform(np.array(test_data))

tests_data = torch.FloatTensor(tests_data)
print(tests_data)

tensor([[-0.9926, -1.0000, -1.0000, -1.0000, -0.5692],
        [-0.8083, -0.8182, -0.8182, -0.8182, -0.1632],
        [-0.6360, -0.6364, -0.6364, -0.6364,  0.2905],
        [-0.4517, -0.4545, -0.4545, -0.4545,  0.8995],
        [-0.2734, -0.2727, -0.2727, -0.2727,  1.2060],
        [-0.0892, -0.0909, -0.0909, -0.0909,  0.9592],
        [ 0.0892,  0.0909,  0.0909,  0.0909,  0.3542],
        [ 0.2734,  0.2727,  0.2727,  0.2727, -0.4896],
        [ 0.4577,  0.4545,  0.4545,  0.4545, -1.1622],
        [ 0.6360,  0.6364,  0.6364,  0.6364, -1.1025],
        [ 0.8202,  0.8182,  0.8182,  0.8182, -0.4657],
        [ 0.9985,  1.0000,  1.0000,  1.0000,  0.1632]])

In [ ]:
predict_h = tests_data.matmul(x_W) + x_b
predict_h

tensor([[12.6326],
        [12.8007],
        [13.1023],
        [13.5830],
        [13.6278],
        [12.7907],
        [11.4319],
        [ 9.6753],
        [ 8.1824],
        [ 7.8472],
        [ 8.3707],
        [ 8.9120]], grad_fn=<AddBackward0>)

In [ ]:
submit=pd.read_csv('seaice_sample.csv')
submit

    month  seaice_extent
0       1            NaN
1       2            NaN
2       3            NaN
3       4            NaN
4       5            NaN
5       6            NaN
6       7            NaN
7       8            NaN
8       9            NaN
9      10            NaN
10     11            NaN
11     12            NaN

In [ ]:
for i in range(len(predict_h)):
  submit['seaice_extent'][i]=predict_h[i].item()

submit

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    month  seaice_extent
0       1      12.632626
1       2      12.800704
2       3      13.102301
3       4      13.582975
4       5      13.627802
5       6      12.790665
6       7      11.431870
7       8       9.675328
8       9       8.182350
9      10       7.847157
10     11       8.370737
11     12       8.912042

In [ ]:
submit.to_csv('submit.csv', index=False, header=True)

In [ ]:
!kaggle competitions submit -c prediction-of-sea-ice -f submit.csv -m "17011885"

100% 270/270 [00:03<00:00, 70.1B/s]
Successfully submitted to Prediction Of Sea Ice